### ISSUE TITLE
E0382 when building with cover feature

### ISSUE THREAD

**Issue by AndydeCleyre** [hrkfdn/ncspot#534]
**Describe the bug**
I tried to build `0.7.1` with the cover feature enabled, on Arch Linux.

<details><summary>Drum roll...</summary>

```
Compiling protobuf v2.14.0
Compiling encoding_rs v0.8.28
Compiling crossbeam-utils v0.7.2
Compiling miniz_oxide v0.4.4
Compiling crossbeam-utils v0.8.4
Compiling num_cpus v1.13.0
Compiling iovec v0.1.4
Compiling net2 v0.2.37
Compiling getrandom v0.2.2
Compiling time v0.1.43
Compiling mio v0.7.11
Compiling xcb v0.8.2
Compiling rand_os v0.1.3
Compiling socket2 v0.3.19
Compiling socket2 v0.4.0
Compiling aho-corasick v0.7.18
Compiling atty v0.2.14
Compiling polling v2.0.3
Compiling dirs-sys-next v0.1.2
Compiling signal-hook-registry v1.3.0
Compiling term_size v0.3.2
Compiling ioctl-rs v0.2.0
Compiling fern v0.6.0
Compiling idna v0.2.3
Compiling idna v0.1.5
Compiling futures-lite v1.11.3
Compiling libpulse-simple-sys v1.16.1
Compiling libdbus-sys v0.2.1
Compiling generic-array v0.14.4
Compiling openssl v0.10.34
Compiling openssl-sys v0.9.63
Compiling native-tls v0.2.7
Compiling nix v0.17.0
Compiling parking_lot_core v0.6.2
Compiling parking_lot v0.9.0
Compiling smallvec v0.6.14
Compiling hyper v0.12.36
Compiling ncurses v5.101.0
Compiling semver v0.11.0
Compiling rand_pcg v0.1.2
Compiling rand_chacha v0.1.1
Compiling num-integer v0.1.44
Compiling quote v0.6.13
Compiling num-complex v0.3.1
Compiling priority-queue v1.1.1
Compiling syn v1.0.72
Compiling bytes v0.4.12
Compiling futures-cpupool v0.1.8
Compiling tokio-executor v0.1.10
Compiling crossbeam-epoch v0.8.2
Compiling crossbeam-queue v0.2.3
Compiling crossbeam-channel v0.5.1
Compiling mio v0.6.23
Compiling backtrace v0.3.59
Compiling flate2 v1.0.20
Compiling rand_core v0.6.2
Compiling uuid v0.8.2
Compiling ahash v0.6.3
Compiling nb-connect v1.2.0
Compiling protobuf-codegen v2.14.0
Compiling clap v2.33.3
Compiling regex v1.5.4
Compiling dirs-next v1.0.2
Compiling signal-hook v0.3.8
Compiling url v2.2.2
Compiling mime_guess v2.0.3
Compiling url v1.7.2
Compiling async-io v1.4.1
Compiling dbus v0.9.2
Compiling cipher v0.2.5
Compiling digest v0.9.0
Compiling crypto-mac v0.11.0
Compiling block-buffer v0.9.0
Compiling pancurses v0.16.1
Compiling rustc_version v0.3.3
Compiling rand v0.6.5
Compiling num-rational v0.3.2
Compiling num-iter v0.1.42
Compiling syn v0.15.44
Compiling tokio-current-thread v0.1.7
Compiling tokio-timer v0.2.13
Compiling tokio-io v0.1.13
Compiling http v0.1.21
Compiling string v0.2.1
Compiling tokio-buf v0.1.1
Compiling crossbeam-deque v0.7.3
Compiling tokio v0.2.25
Compiling rand_chacha v0.3.0
Compiling protobuf-codegen-pure v2.14.0
Compiling synstructure v0.12.4
Compiling darling_core v0.10.2
Compiling platform-dirs v0.3.0
Compiling env_logger v0.6.2
Compiling publicsuffix v1.5.6
Compiling cookie v0.12.0
Compiling serde_derive v1.0.126
Compiling futures-macro v0.3.15
Compiling thiserror-impl v1.0.24
Compiling tokio-macros v1.1.0
Compiling pin-project-internal v1.0.7
Compiling num-derive v0.3.3
Compiling enumflags2_derive v0.6.4
Compiling enum-map-derive v0.4.6
Compiling derivative v2.2.0
Compiling serde_repr v0.1.6
Compiling async-trait v0.1.50
Compiling strum_macros v0.20.1
Compiling aes-soft v0.6.4
Compiling ctr v0.6.0
Compiling hmac v0.11.0
Compiling sha-1 v0.9.5
Compiling dbus-tree v0.9.1
Compiling uuid v0.7.4
Compiling num v0.3.1
Compiling darling_core v0.9.0
Compiling tokio-threadpool v0.1.18
Compiling http-body v0.1.0
Compiling h2 v0.1.26
Compiling tokio-util v0.3.1
Compiling rand v0.8.3
Compiling x11-clipboard v0.3.3
Compiling failure_derive v0.1.8
Compiling zerocopy-derive v0.2.0
Compiling librespot-protocol v0.2.0
Compiling darling_macro v0.10.2
Compiling futures-util v0.3.15
Compiling thiserror v1.0.24
Compiling tokio v1.5.0
Compiling pin-project v1.0.7
Compiling libpulse-sys v1.18.0
Compiling enum-map v0.6.4
Compiling aes v0.6.0
Compiling serde v1.0.126
Compiling aes-ctr v0.6.0
Compiling pbkdf2 v0.8.0
Compiling tokio-tls v0.3.1
Compiling clipboard v0.5.0
Compiling num-bigint v0.4.0
Compiling tempfile v3.2.0
Compiling failure v0.1.8
Compiling darling v0.10.2
Compiling zerocopy v0.3.0
Compiling tracing-futures v0.2.5
Compiling libpulse-binding v2.23.1
Compiling darling_macro v0.9.0
Compiling tokio-reactor v0.1.12
Compiling futures-executor v0.3.15
Compiling tokio-stream v0.1.5
Compiling tokio-util v0.6.6
Compiling dotenv v0.13.0
Compiling chrono v0.4.19
Compiling toml v0.5.8
Compiling serde_json v1.0.64
Compiling enumflags2 v0.6.4
Compiling serde_urlencoded v0.7.0
Compiling serde_urlencoded v0.5.5
Compiling serde_cbor v0.11.1
Compiling wasmer_enumset_derive v0.5.0
Compiling h2 v0.2.7
Compiling futures v0.3.15
Compiling tokio-tcp v0.1.4
Compiling darling v0.9.0
Compiling libpulse-simple-binding v2.23.0
Compiling vergen v3.2.0
Compiling proc-macro-crate v0.1.5
Compiling cookie_store v0.7.0
Compiling wasmer_enumset v1.0.1
Compiling tokio-socks v0.3.0
Compiling tokio v0.1.22
Compiling derive_builder_core v0.5.0
Compiling zvariant_derive v2.6.0
Compiling zbus_macros v1.9.1
Compiling cursive_core v0.2.2
Compiling derive_builder v0.7.2
Compiling hyper v0.13.10
Compiling zvariant v2.6.0
Compiling librespot-core v0.2.0
Compiling cursive v0.16.3
Compiling hyper-tls v0.3.2
Compiling zbus v1.9.1
Compiling hyper-tls v0.4.3
Compiling reqwest v0.9.24
Compiling reqwest v0.10.10
Compiling notify-rust v4.5.1
Compiling librespot-audio v0.2.0
Compiling librespot-metadata v0.2.0
Compiling rspotify v0.10.0
Compiling librespot-playback v0.2.0
Compiling ncspot v0.7.1 (/home/andy/Code/aur/ncspot/src/ncspot-0.7.1)
```
</details>

```rust
warning: use of deprecated struct `cursive::view::ScrollBase`: `ScrollBase` is being deprecated in favor of the view::scroll module.
 --> src/ui/listview.rs:9:5
  |
9 | use cursive::view::ScrollBase;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated struct `cursive::view::ScrollBase`: `ScrollBase` is being deprecated in favor of the view::scroll module.
  --> src/ui/listview.rs:40:16
   |
40 |     scrollbar: ScrollBase,
   |                ^^^^^^^^^^

warning: use of deprecated struct `cursive::view::ScrollBase`: `ScrollBase` is being deprecated in favor of the view::scroll module.
  --> src/ui/listview.rs:57:24
   |
57 |             scrollbar: ScrollBase::new(),
   |                        ^^^^^^^^^^

error[E0382]: borrow of moved value: `cfg`
   --> src/main.rs:205:79
    |
141 |     let cfg: Arc<crate::config::Config> = Arc::new(Config::new());
    |         --- move occurs because `cfg` has type `Arc<Config>`, which does not implement the `Copy` trait
...
188 |         cfg,
    |         --- value moved here
...
205 |     let coverview = ui::cover::CoverView::new(queue.clone(), library.clone(), &cfg);
    |                                                                               ^^^^ value borrowed here after move

error: aborting due to previous error; 3 warnings emitted

For more information about this error, try `rustc --explain E0382`.
error: could not compile `ncspot`

To learn more, run the command again with --verbose.
```

**To Reproduce**

```console
$ git clone https://aur.archlinux.org/ncspot
$ cd ncspot
$ sed -Ei 's/(cargo build --release --locked)$/\1 --features cover/' PKGBUILD
$ makepkg -s
```

**Expected behavior**
I expected the compilation to succeed, with all default features enabled as well as the cover feature.

**System (please complete the following information):**
 - OS: Arch Linux
 - Version: 0.7.1
 - Installed from: AUR, modified

**Comment by hrkfdn** [comment]
Thanks, should be fixed again.

**Comment by MonstrousOgre** [comment]
@hrkfdn I still get this error when installing from crates.io. I'm guessing it hasn't been updated there?

**Comment by hrkfdn** [comment]
Should be out now with 0.7.2

**Comment by MonstrousOgre** [comment]
Working now. Thanks!
