### ISSUE TITLE
Crash on 'save' and 'similar tracks'

### ISSUE THREAD

**Issue by BodomBeach** [hrkfdn/ncspot#661]
When typing s to save or shift+m to find similar tracks, the program crashes

**To Reproduce**
1. ncspot --debug stderr.log
2. press shift+m

**Expected behavior**
Should find similar tracks

**System (please complete the following information):**
 - OS: Linux Mint 20
 - Terminal: Terminator or Konsole
 - Version: 0.9.1
 - Installed from: cargo ( cargo install ncspot)

**Backtrace/Debug log**

> [2021-11-30][16:28:52] [ncspot::spotify_worker] [DEBUG] Worker thread is shutting down, stopping player
[2021-11-30][16:28:52] [librespot_playback::player] [DEBUG] Shutting down player thread ...
[2021-11-30][16:28:52] [librespot_core::session] [DEBUG] drop Dispatch
[2021-11-30][16:28:52] [librespot_playback::player] [DEBUG] command=Stop
[2021-11-30][16:28:52] [mio::poll] [TRACE] deregistering event source from poller
[2021-11-30][16:28:52] [librespot_playback::player] [DEBUG] drop PlayerInternal[1]
[2021-11-30][16:28:52] [librespot_core::session] [DEBUG] drop Session[1]
[2021-11-30][16:28:52] [librespot::component] [DEBUG] drop AudioKeyManager
[2021-11-30][16:28:52] [librespot::component] [DEBUG] drop MercuryManager
[2021-11-30][16:28:52] [librespot_playback::player] [DEBUG] PlayerInternal thread finished.

**Comment by f380cedric** [comment]
I got similar behavior using Shift+m or using the context menu ([Shift+]o->"Similar Tracks").
Bisecting flags 96f2d88696a464a634b9f98fe63bad9594d2dfdf.

**Comment by hrkfdn** [comment]
Thanks for the report. The problem lies here: https://github.com/hrkfdn/ncspot/blob/dbd8ca93bb7115064dd5a52cbdde333d3f1f91e1/src/spotify_api.rs#L333

It seems that track IDs are containing Spotify URIs (`spotify:track:XXXX`) instead of just the ID (`XXXX`). I'll have to investigate if this is a problem in librespot or ncspot. Hoping to release a fix later today.

**Comment by hrkfdn** [comment]
0.9.2 is released, should be fixed now. Thanks for your help!

**Comment by BodomBeach** [comment]
Working great now, thanks for the quick fix !
And great work overall, keep it up !

**Comment by f380cedric** [comment]
Not on my side :( I still have some tracks in my Library for which id is in the form "spotify:track:xxx".

**Comment by hrkfdn** [comment]
@f380cedric Are those single saved tracks? Tracks from albums? Tracks from playlists?

Alternatively you could try clearing the cache `~/.cache/ncspot/*.db` before starting and see if that fixes it.

**Comment by f380cedric** [comment]
You right, it was specific to the track view under Library. Deleting the DBs fixed it :) Thanks

**Comment by hrkfdn** [comment]
Glad it helped, though it should have detected this automatically :|
