### ISSUE TITLE
ncspot UI flickers, no progress bar for song remaining, and backspace in ':search' prompt doesn't work

### ISSUE THREAD

**Issue by ThomasAdam** [hrkfdn/ncspot#934]
**Describe the bug**

A recent upgrade to ncspot 0.11.0 rendered the main UI unusable.  Although ncspot plays songs just fine, the interface flickers continually.  Additionally, there is no progress bar indicator at the bottom of the screen, and when trying to use the backspace key in the `:search` prompt, that does not work, hence it is not possible to delete anything.

This is all within `xterm`.

In investigating this, a `git bisect` between `v0.10.1` (the known last good/working version), and `v0.11.0` indicates that the following commit is where the regression has occurred:

```
commit 726ff760918e244ee8d165c10c1af89c7bceb5d6
Author: Nathan White <13190658+eulerfan271@users.noreply.github.com>
Date:   Fri Aug 5 11:39:06 2022 -0700

    switch to termion as defualt backend

diff --git a/Cargo.toml b/Cargo.toml
index faba492..ab41f7b 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -67,7 +67,7 @@ optional = true
 [features]
 alsa_backend = ["librespot-playback/alsa-backend"]
 cover = ["ioctl-rs"] # Support displaying the album cover
-default = ["share_clipboard", "pulseaudio_backend", "mpris", "notify", "pancurses_backend"]
+default = ["share_clipboard", "pulseaudio_backend", "mpris", "notify", "termion_backend"]
 mpris = ["dbus", "dbus-tree"] # Allow ncspot to be controlled via MPRIS API
 notify = ["notify-rust"] # Show what's playing via a notification
 pancurses_backend = ["cursive/pancurses-backend", "pancurses/win32"]
```

I know the problem will probably be within the `termion` repository -- and I will be investigating that next, but I'm also going to raise this issue here, in case it's not.

If I use a different terminal (such as `alacritty`), then everything works as expected (**the bug does not appear**).  However, UI libraries should be intelligent enough to handle this, so the suggestion of "use a different terminal", would be too glib.

I'm also curious to understand *why* the backend has been changed?

**System (please complete the following information):**
 - OS: Linux
 - Terminal: xterm
 - Version: 0.11.0
 - Installed from: AUR, but Git also broken

**Comment by Bettehem** [comment]
Hi, I am able to reproduce the issue. I tested with Xfce Terminal and Alacritty, and the issue doesn't appear. **However**, when running ncspot inside tmux, the issue appears with both terminals. I was able to record this happening, it looks a bit worse irl but very similar to the recordings:
Alacritty:

https://user-images.githubusercontent.com/3002104/189540705-58474479-5841-4bfc-b1f8-da3482b3dbff.mp4

Xfce Terminal:

https://user-images.githubusercontent.com/3002104/189540709-432f943b-8c56-4864-bb3f-8e750f5515fd.mp4

This didn't happen with the pancurses backend.

**Comment by hrkfdn** [comment]
Looks like this could be related: https://github.com/gyscos/cursive/issues/667

**Comment by hrkfdn** [comment]
Hi there, I have pushed a fix that should hopefully help with this. As I can't reproduce this myself it would be cool if you could report if it helps. Thanks! :)

**Comment by ThomasAdam** [comment]
Hi @hrkfdn 

Yup -- that's fixed this issue, thank you.  I still cannot delete any characters when pressing backspace, when in a `:` prompt, but that's separate to this.

**Comment by hrkfdn** [comment]
@ThomasAdam Hmm, can't really reproduce that backspace issue. Does using a terminal other than xterm also fix this for you?

**Comment by ThomasAdam** [comment]
Hey @hrkfdn,

Yes, alacritty works fine.  I suspect the reason it fails in xterm is down to `cursive` or `termion` not understanding escape sequences correctly.
